// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
/// options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9csBdVKCe364KOAx35lNaiV4EfnA8Org',
    appId: '1:1038631969256:web:09f8671006822434f3445d',
    messagingSenderId: '1038631969256',
    projectId: 'my-cartier-cloud',
    authDomain: 'my-cartier-cloud.firebaseapp.com',
    storageBucket: 'my-cartier-cloud.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbdY2TuhkbRDTgU0EQgB6tRyw-9m3NG7c',
    appId: '1:1038631969256:android:6ca9283949a64be1f3445d',
    messagingSenderId: '1038631969256',
    projectId: 'my-cartier-cloud',
    storageBucket: 'my-cartier-cloud.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcM4xMUnJg8I45ZAklKzGiemsixkiGOD8',
    appId: '1:1038631969256:ios:b8e3fbd9257b52c2f3445d',
    messagingSenderId: '1038631969256',
    projectId: 'my-cartier-cloud',
    storageBucket: 'my-cartier-cloud.firebasestorage.app',
    iosBundleId: 'com.thisara.cartier.myCartier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcM4xMUnJg8I45ZAklKzGiemsixkiGOD8',
    appId: '1:1038631969256:ios:b8e3fbd9257b52c2f3445d',
    messagingSenderId: '1038631969256',
    projectId: 'my-cartier-cloud',
    storageBucket: 'my-cartier-cloud.firebasestorage.app',
    iosBundleId: 'com.thisara.cartier.myCartier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9csBdVKCe364KOAx35lNaiV4EfnA8Org',
    appId: '1:1038631969256:web:cfd46734998a64c2f3445d',
    messagingSenderId: '1038631969256',
    projectId: 'my-cartier-cloud',
    authDomain: 'my-cartier-cloud.firebaseapp.com',
    storageBucket: 'my-cartier-cloud.firebasestorage.app',
  );
}
